WASdev/azure.websphere-traditional.cluster

pom.xml, src/main/arm/createUiDefinition.json, src/main/arm/mainTemplate.json
This PR is to resolve the following issues:
* Issue #10
* Only assign a public IP address to nic of dmgr VM
* Assign private IP addresses to nics of managed nodes
* Remove unnecessary custom regex and validation message for password in `CredentialsCombo` element: it's not related to the PR topic, but small enough to be contained.
The following cases have already been verified before sending out the PR:
* Successfully deployed a tWAS cluster with one dmgr node and one managed node;
* Dmgr node is assigned with a public IP address;
* Managed node is assigned with a private IP address only; 
* User can `ssh` to the managed node VM with the following steps:
* Open port 22 in the network security group;
* `ssh` to the dmgr node VM
* In dmgr node VM: `ssh` to the managed node VM using its …
=> Only assign a public IP address to dmgr VM

pom.xml, src/main/scripts/install.sh
This PR is to resolve the following issues:
* Issue #17
* Open additional required ports for deployment manager, federated application server, node agent & cluster member
The following cases have already been verified before sending out the PR:
* Successfully deployed a cluster with 1 dmgr and 2 managed nodes using Azure CLI & private vm image;
=> Open additional required ports to successfully form a cluster

pom.xml, src/main/scripts/install.sh
This PR is to resolve the 2nd part of the following issue:
* Issue #17
* Open additional required ports for dynamic cluster member
* Change from `tcp` to `udp` for udp ports
The following cases have already been verified before sending out the PR:
* Successfully deployed a dynamic cluster with 1 dmgr and 2 managed nodes using Azure CLI;
* After deployment, 1 cluster member is automatically started, which functions as expected based on cluster configuration;
=> Open missing ports for dynamic cluster

.github/workflows/package.yaml
**Add pipeline to automate artifact building for offer publish**
Step-by-step guidance:
* Use following command to trigger the pipeline
```bash
PERSONAL_ACCESS_TOKEN={your personal token}
REPO_NAME=WASdev/azure.websphere-traditional.cluster
curl --verbose -XPOST -u "WASdev:${PERSONAL_ACCESS_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${REPO_NAME}/actions/workflows/package.yaml/dispatches --data '{"ref": "master"}'
```
* Go to Cluster Repo's action page: https://github.com/WASdev/azure.websphere-traditional.cluster/actions
* Select `Package ARM` under 'All workflows', click on the latest run.
* At the bottom of the action run page, click the artifact and download it for offer publish
Verified in forked …
=> Add pipeline to build artifact

pom.xml, src/main/arm/createUiDefinition.json, src/main/arm/deploy.azcli, src/main/arm/mainTemplate.json, src/main/arm/parameters.json, src/main/scripts/configure-ihs-on-dmgr.sh, src/main/scripts/configure-ihs.sh, src/main/scripts/configure-im.py, src/main/scripts/install.sh, src/main/scripts/pluginutil.sh
This PR is to resolve the following issues:
* Resolve #37 
* Resolve #40 
* Resolve #84 
* Automation scripts to configure IHS on both ihs & dmgr VMs
* ARM template to deploy Azure resources for IHS 
* UI to configure IHS on Azure Portal 
* Enhance text in `createUiDefinition.json` to aid people getting an entitlement
* Use IBM ID rather than IBMid consistently
The following cases have already been verified before sending out the PR. You can have a try using the [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewwasndt91-n-cluster) also.
* Successfully deployed a tWAS cluster with an a working IHS if specified by the user on Azure Portal;
* Successfully installed `DefaultApplication` (shipped with WAS ND installation) …
=> Configure an IBM HTTP Server in the tWAS cluster

README.md, pom.xml, src/main/arm/createUiDefinition.json, src/main/arm/mainTemplate.json, src/main/scripts/configure-ihs-on-dmgr.sh, src/main/scripts/configure-ihs.sh, src/main/scripts/install.sh
This is the 2nd PR sent to cluster repo to completely fix the following issues:
* Address part of #56
* Fix #85
* Fix #39
* Fix #35
The [1st PR](https://github.com/WASdev/azure.websphere-traditional.image/pull/42) sent to image repo has already been merged.
* [Preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewwasndt91-n-cluster);
* Successfully deployed a cluster with 20 worker nodes and an IHS (took ~50 mins) using the above preview link, installed `DefaultApplication`, and visited the application using the IHS;
* Deployed with an invalid IBM ID and all of VMs are emptied as expected.
=> Fix issues 35, 39, 85 and part of 56

README.md, pom.xml, src/main/resources/README.md
The following test cases are passed using the latest twas-nd and ihs base images (9.0.20210726):
* Successfully deployed a static cluster with 1 worker node and 1 IHS, using the entitled IBM ID. Verified that the cluster and IHS works by visiting the installed `DefaultApplication` using IP address of IHS VM.
=> reference new base images which support RHEL 8_4

src/main/arm/createUiDefinition.json, src/main/arm/mainTemplate.json
* Fix #93;
* Append version info to the url of IBM eCustomer Care to get rid of the version info displayed in the bottom of the basic tab;
* Deployed a cluster with public key as authentication type for both twas and ihs vms. Successfully `ssh` into twas and ihs vms using the private key.
=> fix failed to sign into ihs vm using ssh key

README.md, pom.xml, src/main/cli/deploy.azcli
With pull request Azure/azure-javaee-iaas#20 is merged, it's time to move utility scripts that're not part of deployment scripts included in the offer to `src/main/cli` for better organization of code structure.
=> move utility scripts to src/main/cli

pom.xml, src/main/arm/mainTemplate.json, src/main/scripts/configure-ihs-on-dmgr.sh, src/main/scripts/configure-ihs.sh, src/main/scripts/install.sh
This is the 2nd PR to resolve #105, which depends on [another PR](https://github.com/WASdev/azure.websphere-traditional.image/pull/47) opened in the image repo.
* Add timestamps for profile creation, cluster creation and ihs configuration
* Use properties instead of hard-coded values
The following test cases have been passed before opening the above two PRs:
* Successfully created twas-nd and ihs private VM images based on image repo;
* Successfully created a tWAS cluster (1 dmgr, 1 worker node & 1 IHS) by referencing the private images with an entitled IBMid. 
* User can then successfully deploy a default application `DefaultApplication` to the cluster and IHS, which is accessible later;
* Created an empty tWAS cluster (1 dmgr, 1 worker node & 1 IHS) by referencing the private images …
=> Add timestamps for profile creation, cluster creation and ihs configuration

pom.xml, src/main/arm/createUiDefinition.json
This PR is to fix the following issues:
* Resolve #98 
* Add multiple links at the bottom of the home page for user to report issues/get help
* Move version info as parameter of issue tracker url
=> Add multiple links at the bottom of the home page for user to report issues/get help

pom.xml, src/main/arm/createUiDefinition.json, src/main/arm/mainTemplate.json, src/main/arm/parameters.json, src/main/cli/deploy.azcli, src/main/scripts/configure-ihs.sh, src/main/scripts/install.sh
The PR is to resolve #140 and resolve #141 so that the twas-cluster offer can support both entitlement and evaluation usages.
The following test cases are passed before sending out the PR:
* Deployment in **Entitled** mode:
* Successfully deployed a tWAS nd cluster on Azure VMs using an entitled IBMid
* Failed to deploy a tWAS nd cluster on Azure VMs using an invalid IBMid
* Deployment in **Evaluation license** mode:
* Successfully deployed a tWAS nd cluster on Azure VMs without IBMid
Here is the [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewwasndt91-n-cluster) for live testing.
Signed-off-by: Jianguo Ma [jiangma@microsoft.com](mailto:jiangma@microsoft.com)
=> Support entitlement and evaluation editions

docs/howto-update-for-was-fixpack.md
The PR is related to the primary PR WASdev/azure.websphere-traditional.image/pull/59, which adds a link to how-to guide about access the source vm when cicd failed.
=> access the image source vm if cicd failed

docs/howto-update-for-was-fixpack.md
This PR is to reference the guide created by WASdev/azure.websphere-traditional.image/pull/60 to instruct user to clean up the storage account for reducing Azure cost.
=> Reference guide about how to cleanup after image is published

README.md, docs/howto-update-for-was-fixpack.md, pom.xml, src/main/arm/createUiDefinition.json, src/main/bicep/config.json, src/main/bicep/mainTemplate.bicep, src/main/bicep/modules/_pids/_empty.bicep, src/main/scripts/configure-ihs-on-dmgr.sh, src/main/scripts/configure-ihs.sh, src/main/scripts/install.sh
The PR is to resolve the following issues:
* Resolve #167
* Add `Microsoft.Network.VirtualNetworkCombo` to `createUiDefinition.json` so user can create a new VNet or select an existing VNet;
* Update `mainTemplate.bicep` to support creating a new VNet or use the existing VNet per user input
* For the case of using the existing VNet, no public IP address created and assigned to network interface
* Create a private endpoint as a communication channel between the storage account and cluster if ihs is enabled
The following test cases have already been passed before opening the PR:
* Successfully deployed a twas-nd cluster and an IHS with a new VNet on an Azure VM with evaluation license using the preview link below.
* Successfully deployed a twas-nd cluster and an IHS with an existing VNet on …
=> Bring your own VNet

pom.xml, src/main/arm/createUiDefinition.json, src/main/bicep/config.json, src/main/bicep/mainTemplate.bicep
The PR is to add a checkbox which asks user if he/she agrees to IBM contacting his/her company or organization when deploying with an evaluation license:
* Add information box and check box in the UI to check user's agreement
* Deploy an Azure deployment with a pre-defined unique name if user agrees
See details from the relevant issue: WASdev/azure.websphere-traditional.cluster/issues/159.
1. Info box + checkbox:   
1. Info box + checkbox + tooltip of checkbox:
The following test cases have already been passed before opening the PR:
* Deployed a twas-nd cluster and an IHS with evaluation license **with** user's agreement for contacting: the dedicated deployment is created.
* Deployed a twas-nd cluster and an IHS with evaluation license **without** user's agreement for contacting: the …
=> Agree to IBM contacting customer's company or organization

.github/workflows/integration-test.yaml, README.md, docs/howto-update-for-was-fixpack.md, pom.xml, src/main/bicep/mainTemplate.bicep, src/main/cli/deploy.azcli, src/main/scripts/install.sh
The PR is to resolve the following issues by adding a new integration testing pipeline and fixing the deployment hang after upgrading to 9.0.5.13:
* Resolve #171 
* Resolve #174 
See the successful rans of pipeline:
* [integration-test · majguo/azure.websphere-traditional.cluster@31650ca (github.com)](https://github.com/majguo/azure.websphere-traditional.cluster/actions/runs/2990028821)
* [integration-test · majguo/azure.websphere-traditional.cluster@8b3a6d1 (github.com)](https://github.com/majguo/azure.websphere-traditional.cluster/actions/runs/2975966243)
=> Add integration test pipeline and fix deployment hang after upgrade to 9.0.5.13

.github/workflows/integration-test.yaml, .github/workflows/package.yaml, pom.xml
Upgrade versions of external deps used in pipelines by referencing to the centralized config file:
- az-cli
- bicep
- arm-ttk
- azure-javaee-iaas
=> Upgrade versions of external deps used in pipelines by referencing to the centralized config file

docs/howto-update-for-was-fixpack.md
The PR addresses part of the requirements listed in WASdev/azure.websphere-traditional.image/issues/64 by adding instructions about updating twas-nd-cis and ihs-cis vm images.
=> Add instructions about updating cis based images

.gitignore, changebundle.txt~, pom.xml
modified:   .gitignore
modified:   pom.xml
Follow on from #200 
=> On branch edburns-msft-dd-1733484-increment-pom

docs/howto-update-for-was-fixpack.md
The PR addresses part of the requirements listed in WASdev/azure.websphere-traditional.image/issues/64 by adding instructions about updating twas-nd and ihs vm images.
=> Update steps on how to update vm images

.github/workflows/package.yaml, docs/howto-update-for-was-fixpack.md
…
modified:   .github/workflows/package.yaml
=> On branch edburns-msft-ibm-342-end-to-end-automation-documentation Remove conditional restricting publishing to only when run within WASdev.

.github/workflows/integration-test.yaml, .github/workflows/package.yaml, README.md, docs/howto-update-for-was-fixpack.md, pom.xml, src/main/bicep/mainTemplate.bicep, src/main/bicep/modules/_appgateway.bicep, src/main/bicep/modules/_azure-resources/_appGateway.bicep, src/main/bicep/modules/_azure-resources/_keyvault/_keyvaultWithNewCert.bicep
This pull request includes changes to the GitHub Action workflows and Maven configuration in the project. The most significant changes are the removal of some environment variables and the checkout step for `azure-javaee-iaas` in the GitHub workflows, the addition of input parameters and Maven environment setup in the workflows, and the update of Maven parent version and the addition of GitHub Packages repository in the `pom.xml` file. 
Changes to GitHub workflows:
* `.github/workflows/integration-test.yaml` and `.github/workflows/package.yaml`: Removed environment variables `azCliVersion`, `refArmttk`, and `refJavaee`, and the checkout step for `azure-javaee-iaas`. Added Maven environment setup steps and input parameters for the workflows. 
Changes to Maven configuration:
* …
=> Remove azure javaee in workflows

pom.xml, src/main/bicep/mainTemplate.bicep, src/main/bicep/modules/_appgateway.bicep, src/main/bicep/modules/_azure-resources/_appGateway.bicep, src/main/bicep/modules/_azure-resources/_keyvault/_keyvaultWithNewCert.bicep, src/main/bicep/modules/_deployment-scripts/_dsPostDeployment.bicep, src/main/bicep/modules/_uami/_roleAssignment.bicep, src/main/bicep/modules/_uami/_uamiAndRoles.bicep, src/main/resources/azure-common.properties
Refactor: refactor bicep scripts to use version placeholders so all the versions can be managed in the [azure-common.properties](https://github.com/WASdev/azure.websphere-traditional.cluster/blob/5c67c60e244a5c566956594362219804427a0405/src/main/resources/azure-common.properties) file.
=> Refactor: Configure Bicep Apiversions with properties file

.github/workflows/integration-test.yaml, .github/workflows/package.yaml, pom.xml, src/main/bicep/modules/_uami/_uamiAndRoles.bicep
If I try to do following steps, it will fail.
Step 1. Deploy current offer in resource group rg-a and region east us
Step 2. Delete resource group rg-a
Step 3. Deploy current offer in resource group rg-a and region west us
And this PR is used to fix this bug.
- [Package ARM and Update Offer Artifact #36](https://github.com/azure-javaee/azure.websphere-traditional.cluster/actions/runs/9065174969)
- [integration-test #37](https://github.com/azure-javaee/azure.websphere-traditional.cluster/actions/runs/9065171803)
=> BugFix: Offers can' be redeployed with the same resource group as before with different region in the same subscription

pom.xml, src/main/bicep/mainTemplate.bicep
See [Task-688](https://dev.azure.com/was-azure/was-azure/_workitems/edit/688) for detailed description.
The branch of [PR/250](https://github.com/WASdev/azure.websphere-traditional.cluster/pull/250)  was force-pushed the from 5c67c60 to 2dc5eed
But the push introduced [changes](https://github.com/WASdev/azure.websphere-traditional.cluster/compare/5c67c60e244a5c566956594362219804427a0405..2dc5eed65570e35bcb118352476022e86c8f823c) which were unexpected.
[Test-run-9462338745](https://github.com/azure-javaee/azure.websphere-traditional.cluster/actions/runs/9462338745)
=> Fix Error after PR https://github.com/WASdev/azure.websphere-traditional.cluster/pull/248

src/main/resources/azure-common.properties
Updating `Microsoft.KeyVault/vaults` and `Microsoft.KeyVault/vaults/secrets` to `2023-07-01` to fix  apiVersions should be recent error.
=> Fix apiVersions should be recent error

.github/workflows/integration-test.yaml, pom.xml, src/main/bicep/modules/_azure-resources/_keyvault/_keyvaultWithNewCert.bicep, src/main/scripts/install.sh
This PR targets to fix #260, which resolves the certificate hostname verification error due to the mismatch between the hostname (short name) included in SAN and the hostname (FQDN) of the cluster member that IHS is trying to route http requests to.
Besides, it also includes a few enhancements which are not related to the mentioned issue:
* fail curl command on http errors
* disable rbac auth explicitly as access policy auth is used in key vault
Pipeline with changes of the PR run successfully: [integration-test](https://github.com/majguo/azure.websphere-traditional.cluster/actions/runs/13299336936)
=> Fix tWAS cluster IHS issue

.github/workflows/integration-test.yaml, .github/workflows/package.yaml
In light of recent incidents involving GitHub Actions ( [https://www.stepsecurity.io/blog/reviewdog-github-actions-are-compromised](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fwww.stepsecurity.io%2fblog%2freviewdog-github-actions-are-compromised&data=05%7c02%7cEdward.Burns%40microsoft.com%7c2e164dbc41814a70b33808dd827ed367%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c638810203429735777%7cUnknown%7cTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7c0%7c%7c%7c&sdata=vi16rlxw83McXqhRG1wMrm4LQ4i26aSyHYWywOPY9K8%3D&reserved=0), [https://www.theregister.com/2025/03/17/supply_chain_attack_github/](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fwww.theregister.com%2f2025%2f03%2f17%2fsupply_chain_attack_git …
=> Update actions version with pinned hash value 
