WASdev/azure.websphere-traditional.cluster

pom.xml
src/main/arm/createUiDefinition.json

This PR is to resolve the following issues:
* Issue #7
* Modify parameter name/tooltip based on IBM's review;
* Use a checkbox to ask user to accept the IBM License Agreement;
The following cases have already been verified before sending out the PR:
* The changes of `createUiDefinition.json` has been verified in the Azure [Create UI Definition Sandbox](https://portal.azure.com/?feature.customPortal=false#blade/Microsoft_Azure_CreateUIDef/SandboxBlade)
* Template unit tests

Address comments from UI content review

---

pom.xml
src/main/arm/createUiDefinition.json

Address open issues to resolve #23

---

README.md

modified:   README.md
Fixes #42.

On branch edburns-msft-42-crosslink-repos Link to base image repository.

---

pom.xml
src/main/arm/mainTemplate.json

modified:   pom.xml
- Define property for image.version.
modified:   src/main/arm/mainTemplate.json
- Use property image.version.

On branch edburns-msft-46-pin-version Fixes #46.

---

pom.xml
src/main/arm/mainTemplate.json

This is the 2nd PR to resolve #43. 
The 1st PR is issued to image repo: https://github.com/WASdev/azure.websphere-traditional.image/pull/37.
Local testing is passed before sending out the PR.

Use space to separate IBMid credential

---

src/main/arm/createUiDefinition.json

modified:   src/main/arm/createUiDefinition.json

On branch edburns-msft-35-error-message Use ibm.biz URL for entitlement link.

---

README.md

On branch edburns-msft-crosslinks-aro-aks Add crosslinks

---

pom.xml

Update versions for tWAS 9.0.5.9.
Signed-off-by: Ranjan Kumar (rk@us.ibm.com)

Update versions for tWAS 9.0.5.9

---

README.md

On branch edburns-msft-add-link-to-singleserver Add link to single server repo in README

---

.github/workflows/package.yaml
README.md
docs/howto-update-for-was-fixpack.md
pom.xml
src/main/arm/mainTemplate.json
src/main/resources/README.md

This PR is to resolve #128 by referencing new base images `9.0.20211220` for both `twas-nd` and `ihs`.
The following test cases are passed before sending out the PR:
* Successfully deploy a tWAS cluster with the [preview link](https://portal.azure.com/#create/microsoft_javaeeonazure_test.20191212-arm-rhel-was-nd-v9-cluster-previewwasndt91-n-cluster)
* Observed that dmgr, managed node and ihs server are all upgraded to version `9.0.5.10`:
* WebSphere integrated solution console:
* dmgr: `/datadrive/IBM/WebSphere/ND/V9/bin/versionInfo.sh`
```
WVER0010I: Copyright (c) IBM Corporation 2002, 2012; All rights reserved.
WVER0012I: VersionInfo reporter version 1.15.1.48, dated 2/8/12
--------------------------------------------------------------------------------
IBM WebSphere Product …
```

Reference to new base images

---

pom.xml
src/main/arm/createUiDefinition.json
src/main/arm/mainTemplate.json
src/main/scripts/configure-ihs.sh
src/main/scripts/install.sh

This PR is related to issue WASdev/azure.websphere-traditional.singleserver/issues/8, which targets to apply the content review changes to the tWAS cluster offer.

Update content text per review comments

---

pom.xml
src/main/arm/createUiDefinition.json

Update license text

---

src/main/arm/createUiDefinition.json

modified:   src/main/arm/createUiDefinition.json
Fixes #197

On branch edburns-msft-dd-1697922-update-aag-info-link Fixes #197 .

---

README.md
src/main/resources/marketing-artifacts/partner-center.html

…
modified:   README.md
new file:   src/main/resources/marketing-artifacts/partner-center.html

On branch edburns-msft-em-2763-externalize-verbiage Extracted verbiage from Partner Center

---

.github/workflows/package.yaml

Automate the artifact update step for offer publishing

Update package pipeline

---

.github/workflows/package.yaml

Bugfix for missing secret reference.

Pipeline bugfix

---

.github/workflows/integration-test.yaml
test/deploy-app.py.template
test/deploy-app.sh

The PR is to enhance the existing integration test pipeline by deploying a sample CRUD app [Azure-Samples/websphere-cafe](https://github.com/Azure-Samples/websphere-cafe).
See the successful workflow run [integration-test](https://github.com/majguo/azure.websphere-traditional.cluster/actions/runs/4674719875).

Enhance the integration test pipeline to support app deployment

---

pom.xml

On branch edburns-msft-ibm-266-increment-pom

---

docs/howto-update-for-was-fixpack.md

modified:   docs/howto-update-for-was-fixpack.md

On branch main Reference pid doc.

---

src/main/bicep/mainTemplate.bicep

[***"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'eastus' and API version '2023-01-01' for type 'privateEndpoints'. The supported api-versions are '2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-01-01, 2020-03-01, 2020-04-01, 2020-05-01, 2020-06-01, 2020-07-01, 2020-08-01, 2020-11-01, 2021-01-01, 2021-02-01, 2021-03-01, 2021-04-01, 2021-05-01, 2021-06-01, 2021-08-01, 2021-12-01, 2022-01-01, 2022-05-01, 2022-07-01, 2022-09-01, 2022-11-01, 2023-02-01, 2023-04-01, 2023-05-01, 2023-06-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, …

Update storage version

---

pom.xml

For https://github.com/WASdev/azure.websphere-traditional.cluster/issues/228

Update version for 9.0.5.17

---

src/main/bicep/modules/_deployment-scripts/_dsPostDeployment.bicep
src/main/bicep/modules/_uami/_uamiAndRoles.bicep

For https://github.com/WASdev/azure.websphere-traditional.cluster/issues/239

Update Api versions

---

pom.xml

On branch edburns-msft-ibm-608-increment-pom Increment pom.

---

.github/workflows/integration-test.yaml
.github/workflows/package.yaml

This pull request includes several updates to the GitHub Actions workflows, primarily focusing on improving the integration test workflow by adding new parameters and updating the deployment process for PostgreSQL databases. Additionally, there is a minor update to the package workflow.
* Added a new input parameter `location` to specify the location of Azure resources, with a default value of 'eastus'. (`.github/workflows/integration-test.yaml`)
* Updated the `location` environment variable to use the new input parameter or default to 'eastus'. (`.github/workflows/integration-test.yaml`)
* Changed the deployment process to use Azure Database for PostgreSQL Flexible Server instead of the standard server. (`.github/workflows/integration-test.yaml`)
* Modified the database user …

CICD pipeline enhancements
